// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseInputFile() {
  return window['go']['main']['App']['ChooseInputFile']();
}

export function CreateDotGraph(arg1) {
  return window['go']['main']['App']['CreateDotGraph'](arg1);
}

export function GetDotGraphs() {
  return window['go']['main']['App']['GetDotGraphs']();
}

export function PerformgSpan() {
  return window['go']['main']['App']['PerformgSpan']();
}

export function ValidateInputFile() {
  return window['go']['main']['App']['ValidateInputFile']();
}
