// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {graph} from '../models';
import {main} from '../models';

export function ChooseInputFile():Promise<void>;

export function CreateDotGraph(arg1:graph.Graph_string_string_):Promise<string>;

export function GetDotGraphs():Promise<Array<string>>;

export function PerformgSpan():Promise<main.InputFile>;

export function ValidateInputFile():Promise<boolean>;
