// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {graph} from '../models';

export function ChooseInputFile():Promise<void>;

export function CreateDotGraph(arg1:graph.Graph_string_string_):Promise<void>;

export function GetDotGraph():Promise<string>;

export function ValidateInputFile():Promise<boolean>;
