// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDotGraph():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function UploadFile(arg1:Record<string, any>):Promise<string>;
